services:
  app:
    container_name: app
    build:
      context: ./src/api/app
    networks:
      test-network:
    environment:
      MONGODB_ATLAS_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: service-catalogue
    networks:
      test-network:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  test:
    build:
      context: ./src/api/test
    environment:
      - SERVICE_UNDER_TEST_HOSTNAME=app:3000
    entrypoint: sh -c "ls -la ./features && npm install && ./node_modules/.bin/cucumber-js ./features/**/*.feature --exit"
    networks:
      test-network:
    depends_on:
      - app
  web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./src/web:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_SERVICE_METADATA_URL=${SERVICE_METADATA_URL}
    networks:
      - test-network
networks:
  test-network:
    driver: bridge
volumes:
  mongodb_data:
